# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e26f43a91c0c27f00c5d0af91114ff1930113a9681e0787647a08745d046a57f6b84b44c95d56f2b1629c9ec74dd84cd25a81aa8c723104d3f3e3a9c39ff80f5

test:
  secret_key_base: c046992faf80689db09fdc234b335f4fbfce6b12e6952445d0742a4b128004b2d3d962bafb842012940dd7214006b8722ac4af8bf38d75b26fa5801c728d3001

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
